#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define TAILLE_BLOC 34

// On définit nos variables globales
enum{HAUT,BAS,GAUCHE,DROITE};
enum{VIDE,MUR,SACHA,ROCHER,VILAIN};

#endif // CONSTANTES_H_INCLUDED
